/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebDesignRouteImport } from './routes/services.web-design'
import { Route as ServicesPrinterRouteImport } from './routes/services.printer'
import { Route as ServicesNetworkingRouteImport } from './routes/services.networking'
import { Route as ServicesLaptopRouteImport } from './routes/services.laptop'
import { Route as ServicesDigitalMarketingRouteImport } from './routes/services.digital-marketing'
import { Route as ServicesCctvRouteImport } from './routes/services.cctv'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDesignRoute = ServicesWebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPrinterRoute = ServicesPrinterRouteImport.update({
  id: '/printer',
  path: '/printer',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesNetworkingRoute = ServicesNetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLaptopRoute = ServicesLaptopRouteImport.update({
  id: '/laptop',
  path: '/laptop',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDigitalMarketingRoute =
  ServicesDigitalMarketingRouteImport.update({
    id: '/digital-marketing',
    path: '/digital-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCctvRoute = ServicesCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/cctv': typeof ServicesCctvRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/laptop': typeof ServicesLaptopRoute
  '/services/networking': typeof ServicesNetworkingRoute
  '/services/printer': typeof ServicesPrinterRoute
  '/services/web-design': typeof ServicesWebDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/cctv': typeof ServicesCctvRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/laptop': typeof ServicesLaptopRoute
  '/services/networking': typeof ServicesNetworkingRoute
  '/services/printer': typeof ServicesPrinterRoute
  '/services/web-design': typeof ServicesWebDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/cctv': typeof ServicesCctvRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/laptop': typeof ServicesLaptopRoute
  '/services/networking': typeof ServicesNetworkingRoute
  '/services/printer': typeof ServicesPrinterRoute
  '/services/web-design': typeof ServicesWebDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/cctv'
    | '/services/digital-marketing'
    | '/services/laptop'
    | '/services/networking'
    | '/services/printer'
    | '/services/web-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/cctv'
    | '/services/digital-marketing'
    | '/services/laptop'
    | '/services/networking'
    | '/services/printer'
    | '/services/web-design'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/cctv'
    | '/services/digital-marketing'
    | '/services/laptop'
    | '/services/networking'
    | '/services/printer'
    | '/services/web-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-design': {
      id: '/services/web-design'
      path: '/web-design'
      fullPath: '/services/web-design'
      preLoaderRoute: typeof ServicesWebDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/printer': {
      id: '/services/printer'
      path: '/printer'
      fullPath: '/services/printer'
      preLoaderRoute: typeof ServicesPrinterRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/networking': {
      id: '/services/networking'
      path: '/networking'
      fullPath: '/services/networking'
      preLoaderRoute: typeof ServicesNetworkingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/laptop': {
      id: '/services/laptop'
      path: '/laptop'
      fullPath: '/services/laptop'
      preLoaderRoute: typeof ServicesLaptopRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/digital-marketing': {
      id: '/services/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/services/digital-marketing'
      preLoaderRoute: typeof ServicesDigitalMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cctv': {
      id: '/services/cctv'
      path: '/cctv'
      fullPath: '/services/cctv'
      preLoaderRoute: typeof ServicesCctvRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCctvRoute: typeof ServicesCctvRoute
  ServicesDigitalMarketingRoute: typeof ServicesDigitalMarketingRoute
  ServicesLaptopRoute: typeof ServicesLaptopRoute
  ServicesNetworkingRoute: typeof ServicesNetworkingRoute
  ServicesPrinterRoute: typeof ServicesPrinterRoute
  ServicesWebDesignRoute: typeof ServicesWebDesignRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCctvRoute: ServicesCctvRoute,
  ServicesDigitalMarketingRoute: ServicesDigitalMarketingRoute,
  ServicesLaptopRoute: ServicesLaptopRoute,
  ServicesNetworkingRoute: ServicesNetworkingRoute,
  ServicesPrinterRoute: ServicesPrinterRoute,
  ServicesWebDesignRoute: ServicesWebDesignRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
