/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPrinterRouteImport } from './routes/services.printer'
import { Route as ServicesLaptopRouteImport } from './routes/services.laptop'
import { Route as ServicesCctvRouteImport } from './routes/services.cctv'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrinterRoute = ServicesPrinterRouteImport.update({
  id: '/printer',
  path: '/printer',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLaptopRoute = ServicesLaptopRouteImport.update({
  id: '/laptop',
  path: '/laptop',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCctvRoute = ServicesCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/cctv': typeof ServicesCctvRoute
  '/services/laptop': typeof ServicesLaptopRoute
  '/services/printer': typeof ServicesPrinterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/cctv': typeof ServicesCctvRoute
  '/services/laptop': typeof ServicesLaptopRoute
  '/services/printer': typeof ServicesPrinterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/cctv': typeof ServicesCctvRoute
  '/services/laptop': typeof ServicesLaptopRoute
  '/services/printer': typeof ServicesPrinterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/cctv'
    | '/services/laptop'
    | '/services/printer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/cctv'
    | '/services/laptop'
    | '/services/printer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/cctv'
    | '/services/laptop'
    | '/services/printer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/printer': {
      id: '/services/printer'
      path: '/printer'
      fullPath: '/services/printer'
      preLoaderRoute: typeof ServicesPrinterRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/laptop': {
      id: '/services/laptop'
      path: '/laptop'
      fullPath: '/services/laptop'
      preLoaderRoute: typeof ServicesLaptopRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cctv': {
      id: '/services/cctv'
      path: '/cctv'
      fullPath: '/services/cctv'
      preLoaderRoute: typeof ServicesCctvRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCctvRoute: typeof ServicesCctvRoute
  ServicesLaptopRoute: typeof ServicesLaptopRoute
  ServicesPrinterRoute: typeof ServicesPrinterRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCctvRoute: ServicesCctvRoute,
  ServicesLaptopRoute: ServicesLaptopRoute,
  ServicesPrinterRoute: ServicesPrinterRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
